import './js/axios-fetch.js';
import './js/book-id.js';
import './js/categories-list.js';
import './js/category-book.js';
import './js/create-markup.js';
import './js/header.js';
import './js/home.js';
import './js/markup-by-category.js';
import './js/mobile-menu.js';
import './js/modal.js';
import './js/top-books.js';
// import './js/shopping-list.js';
import './js/sup-ukraine.js';
import './js/firebase.js';
